version: '3'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/opt/go/code
      - ~/etc/localtime:/opt/ucare/etc/localtime
      - ~/etc/timezone:/opt/ucare/etc/timezone
    command: ["tail -f /dev/null"]
    ports:
      - 3721:8000